apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld-container
        image: 669813892999.dkr.ecr.us-east-1.amazonaws.com/cdso:versionhere
        ports:
        - containerPort: 8000
